### ISSUE TITLE
Only Show Same Error One Time

### ISSUE THREAD

**Issue by triwav** [TwitchBronBron/brightscript-language#10]
Certain errors show up for each file they were included in. For example this issue: https://github.com/sjbarag/brs/issues/177
If the promise library is included in multiple files it will give the `Function parameter 'callback' is of invalid type 'function' ` error once for each file it's included in.

**Comment by TwitchBronBron** [comment]
This was fixed in release `0.1.13`. And since I know you actually wanted to see this in [vscode-brightscript-language](https://github.com/twitchbronbron/vscode-brightscript-language), this fix is present in [release 1.9.0-beta4](https://github.com/TwitchBronBron/vscode-brightscript-language/releases/tag/v1.9.0-beta4)
